### ISSUE TITLE
Afspraken maken met het team

### ISSUE THREAD

**Issue by Jesse-Kramer** [Jesse-Kramer/tumi-mundo#8]
- Communicatie, 
- Teamcanvas,
- Code-conventies, 
- Workflow (branching / forks / reviews)

**Comment by lemuelmgsn** [comment]
Onze teamcanvas:

https://miro.com/app/board/uXjVLboGvTo=/

![Image](https://github.com/user-attachments/assets/b413360f-5373-44c4-a9db-bad44654d660)

**Comment by Jesse-Kramer** [comment]
Communicatie is opgezet, we gebruiken teams.

**Comment by Jesse-Kramer** [comment]
[Code conventies](https://github.com/Jesse-Kramer/tumi-mundo/wiki/Code-conventies) zijn ook opgezet.
Workflow is ook opgezet
